### ISSUE TITLE
Test code

### ISSUE THREAD

**Issue by Theodore-xs** [dsx0511/3DMOTFormer#1]
Hello, may I ask how to use a trained 3DMOTFormer for inference on the nuScenes test set? Is there any code displayed?

**Comment by dsx0511** [comment]
Hi, the code for inference on the test set is available. You can run `train.py` with `--eval_only` argument and provide the checkpoint in the config file (`'resume': CHECKPOINT_PATH`). 

This will run the inference, export results in nuscenes json format, and run evaluation. As the test set cannot be evaluated locally and the annotations are not available, the script will raise an error after exporting the json file. Then you can upload the json file to nuscenes evaluation server to get evaluation results.
