### ISSUE TITLE
detection json on mini data

### ISSUE THREAD

**Issue by KexianShen** [dsx0511/3DMOTFormer#2]
Hi, do you know where to download the detection outputs of NuScenes mini data? Thank.

**Comment by dsx0511** [comment]
Hi, sorry for the late response. The nuscenes mini data is a subset of the full dataset, please refer to [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/splits.py) to filter out the mini set.

**Comment by KexianShen** [comment]
Thanks.
