### ISSUE TITLE
Is there a ros version?

### ISSUE THREAD

**Issue by Pradur241** [dsx0511/3DMOTFormer#3]
Hi, thanks for your work! I would like to ask, how is this project in terms of indoor pedestrian tracking performance? Does it need to be retrained?

BTW, is there a ros project for this?

**Comment by dsx0511** [comment]
Unfortunately, this paper is not targeted at indoor scenes or the ROS project but only for autonomous driving using public datasets. It can be used for indoor pedestrian tracking, but you need to train it on your own dataset.

**Comment by Pradur241** [comment]
Thanks.
