### ISSUE TITLE
May I ask if you can provide model weights

### ISSUE THREAD

**Issue by Jiachenyin1** [dsx0511/3DMOTFormer#4]
I want to check something,pls

**Comment by dsx0511** [comment]
Hi, sorry that we can't publish the trained model weights. 3DMOTFormer is not memory demanding (only 5-6 GB with BS 8) and very fast to train (less than 1 day on an 2080Ti in my experience). Therefore we don't provide model weights because it needs a lot of internal approval process.

**Comment by Jiachenyin1** [comment]
亲~邮件已经收到啦，我会及时查看的

**Comment by Jiachenyin1** [comment]
亲~邮件已经收到啦，我会及时查看的
