### ISSUE TITLE
请问是只需要下载nuscens的meta数据吗？

### ISSUE THREAD

**Issue by eggman-1024** [dsx0511/3DMOTFormer#5]
![1719645114229](https://github.com/dsx0511/3DMOTFormer/assets/79270109/d427f699-ca49-45ec-a9ff-dcc134b2b881)
如上图所示：只需要下载meta数据吗？
如下图suo'shi所示：只需要下载红色框里的数据吗？怎么感觉绿色框数据也得下载呢？
![1719645200108](https://github.com/dsx0511/3DMOTFormer/assets/79270109/84d8acb1-32e6-4a0e-af01-98b350531d04)

**Comment by dsx0511** [comment]
绿色框里的内容主要包括图像，点云等sensor data，而我们训练中只需要任意detector的结果（可以下载到，见README）以及ground truth（在meta data里），只有可视化时才需要绿色框中的sensor data。

**Comment by eggman-1024** [comment]
感谢作者大大！但是训练的时候咋报错说找不到那些sensor data嘞？

**Comment by dsx0511** [comment]
我们暂时没有测试过只下载meta data来训练，如果没有sensor data，nuscenes-devkit在读取数据集时有可能会报错。这种情况下建议直接下载整个数据集。

**Comment by eggman-1024** [comment]
好的好的！（好不容易逮到作者大佬）有几个问题不清楚：
1.所以说训练还是需要整个数据集的意思吧？
2.数据集sensor data只需要点云就可以了吧？
3.请问您开源的代码里有可视化预览代码吗？
十分感谢您的回答！

**Comment by dsx0511** [comment]
训练需要整个数据集，但是只需要meta data而不需要点云。训练时报错找不到sensor data不是因为我们的模型需要sensor data，而是nuscenes devkit在找不到sensor data的情况下会报错。你可以通过修改代码来解决这个问题，但是更简单的解决方法就是直接下载整个数据集。我们没有开源自己的可视化代码，需要可视化的话可以参考[PF-Track](https://github.com/TRI-ML/PF-Track/blob/main/documents/visualization.md).

**Comment by eggman-1024** [comment]
okk，懂了，就是说您的工作专注于tracking而不是detection，所以只需要meta data(标注的detection信息)。

**Comment by dsx0511** [comment]
是的，这篇文章不涉及detection

**Comment by eggman-1024** [comment]
十分感谢
